# -*- coding: utf-8 -*-
{
    'name': "redeemly_pin_management",
    'summary': """Redeemly Pin Management""",
    'description': """""",
    'author': "Redeemly",
    'website': "http://www.redeemly.com",
    'version': '0.1',
    # any module necessary for this one to work correctly
    'depends': ['base',
                'stock',
                'web_domain_field',
                'base_setup',
                'auth_jwt',
                'redeemly_utils',
                'contacts',
                'ir_attachment_s3',
                'account',
                'sale',
                'mail',
                'account_move_name_sequence'
                ],
    # always loaded
    'data': [
        'data/jwt_validator.xml',
        'data/voucher_type_data.xml',
        'data/wallet.xml',
        'data/email_templates.xml',
        'data/sequence_data.xml',
        'data/cron_job_redeem_history.xml',
        'data/cron_jobs.xml',
        'data/fees_account.xml',
        'data/email_templates_v1.xml',
        'data/cron_job_v1.xml',
        'data/invoice_request_cron_jobs.xml',
        'data/merchant_taxes.xml',
        'data/stock_history_job.xml',
        'data/notification.xml',
        'data/email_template_notification.xml',
        'data/sub_merchant_permission.xml',
        'data/serial_batch_cron_jobs.xml',
        'views/res_users.xml',
        'views/product.xml',
        'views/product_serials.xml',
        'views/package.xml',
        'views/generation_requests.xml',
        'views/invoice_requests_view.xml',
        'views/package_codes.xml',
        'views/pin_management_bank_request.xml',
        'views/merchant_package_invites.xml',
        'views/menus.xml',
        'views/res_config_setting.xml' ,
        'wizard/voucher_type_fields_value_edit.xml',
        'security/ir.model.access.csv',
        'wizard/confirm_merchant_bank_transfer.xml',
        'views/ui_login_customize.xml',
        'views/daily_income_report.xml',
        'views/details_sales_report_view.xml',
        'views/redeem_history_log.xml',
        'views/account_move_view_inherited.xml',
        'views/batch_serials_view.xml',
        'views/stock_history_view.xml',
        'views/integration_logs.xml',
        'views/netdargon_slider_views.xml',
        'views/sale_order.xml'
    ],
    'assets': {
        'web.assets_frontend': [
        ],
        'web.assets_backend': [
            'redeemly_pin_management/static/src/js/json_widget.js',
        ],
        'web.assets_qweb': [
            'redeemly_pin_management/static/src/xml/json_widget.xml',
        ],
    },
    'license': 'LGPL-3',
}
